package test;

import java.io.IOException;
import java.text.ParseException;
import java.util.List;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;

import ConnectionManager.ApproveCharityRequests;
import ConnectionManager.Charity;

/*
 * This test case is for the uclAdmin.jsp, requests tab.
 * This tests that the table generated by the jsp program contains
 * the equivalent data in the xml file (represents DB data)
 */
public class RequestTabTest {
	WebDriver driver;

	@Before
	public void setUp(){
		//driver = new HtmlUnitDriver();

		//driver = new FirefoxDriver();

		System.setProperty("webdriver.chrome.driver","lib/chromedriver/chromedriver.exe");
		driver = new ChromeDriver();

	}

	@Test
	public void test() {
        driver.get("http://localhost:8080/CharityWare/uclAdmin.jsp");

        List<Charity> charityFromXML;
		try {
			// get data from xml
			charityFromXML = ApproveCharityRequests.httpGet("http://localhost:8080/CharityWare/REST/charity/charities");
			String charityNameFromXML = charityFromXML.get(0).getCharityName();
			String regNumFromXML = charityFromXML.get(0).getRegistrationNo();
			String charityEmailFromXML = charityFromXML.get(0).getEmail();
			String purposeFromXML = charityFromXML.get(0).getCharityDescription().trim();

			// get data from web page
			WebElement requestTable = driver.findElement(By.className("resultSet"));
			WebElement charityName = requestTable.findElement(By.xpath("tbody/tr[2]/td[2]"));
			WebElement regNum = requestTable.findElement(By.xpath("tbody/tr[2]/td[3]"));
			WebElement charityEmail = requestTable.findElement(By.xpath("tbody/tr[2]/td[4]"));
			WebElement purpose = requestTable.findElement(By.xpath("tbody/tr[2]/td[5]"));

			// check equivaence
			Assert.assertTrue("charity name match", charityName.getText().equals(charityNameFromXML));
			Assert.assertTrue("registration num match", regNum.getText().equals(regNumFromXML));
			Assert.assertTrue("charity email match", charityEmail.getText().equals(charityEmailFromXML));
			Assert.assertTrue("puropse match", purpose.getText().trim().equals(purposeFromXML));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@After
	public void close(){
		driver.close();
	}

}
